name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    name: Validate HACS
    steps:
      - uses: "actions/checkout@v4"
      
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  validate-hassfest:
    runs-on: "ubuntu-latest"
    name: Validate with hassfest
    steps:
      - uses: "actions/checkout@v4"
      
      - name: Run hassfest
        uses: "home-assistant/actions/hassfest@master"

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install pytest pytest-asyncio
          pip install homeassistant
      
      - name: Run tests
        run: |
          pytest tests/ -v